### ISSUE TITLE
Error! Bad return status for module build on kernel: 4.19.0-6-amd64 (x86_64)

### ISSUE THREAD

**Issue by zyxmon** [Nyr/wireguard-install#27]
This looks like a bug in wireguard code:
```
Error! Bad return status for module build on kernel: 4.19.0-6-amd64 (x86_64)
Consult /var/lib/dkms/wireguard/1.0.20201112/build/make.log for more information.
dpkg: ошибка при обработке пакета wireguard-dkms (--configure):
 installed wireguard-dkms package post-installation script subprocess returned error exit status 10

```
In the make.log:
```
  CC [M]  /var/lib/dkms/wireguard/1.0.20201112/build/socket.o
/var/lib/dkms/wireguard/1.0.20201112/build/socket.c: In function ‘send6’:
/var/lib/dkms/wireguard/1.0.20201112/build/socket.c:139:20: error: ‘const struct ipv6_stub’ has no member named ‘ipv6_dst_lookup_flow’; did you mean ‘ipv6_dst_lookup’?
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
make[3]: *** [/usr/src/linux-headers-4.19.0-6-common/scripts/Makefile.build:309: /var/lib/dkms/wireguard/1.0.20201112/build/socket.o] Ошибка 1

```
Script was run on debian 10:
```
~# cat /etc/debian_version
10.7

```

**Comment by crevice** [comment]
Same error here, wireguard-1.0.20201221, Debian 10.1, kernel 4.19.0-6-amd64

**Comment by Nyr** [comment]
This is something which can happen from time to time with DKMS until a `wireguard-dkms` package update or a manual fix is applied.

It will not happen anymore with Debian 11 including the WireGuard module natively in the kernel.

Thanks for providing the fix @crevice.
